### ISSUE TITLE
Do we need to split longer code blocks?

### ISSUE THREAD

**Issue by BenjaminRodenberg** [precice/precice.github.io#300] opened 2023-11-14 10:33 UTC
I stumbled across 74e377cece4a221e00b5c56b1db3942ec70a6272 when working on https://github.com/precice/precice.github.io/pull/262 and was wondering this generally needs to be done for longer code blocks:

https://github.com/precice/precice.github.io/blob/cb25b142995568e635698afe8efd12c388f9cf2a/pages/docs/couple-your-code/couple-your-code-porting-v2-3.md?plain=1#L19

I also briefly discussed this issue with @uekerman and @MakisH.

@chlorenz can you help us here?

I think we should also have some form of documentation about this. Therefore, I'm also opening this issue.

**Comment by uekerman** [comment] 2024-04-29 15:15
duplicate of #388

**Closed as completed** 2024-04-29 15:16 UTC
Labels: question, technical
